// Lucide icon font mapping
export const Lucide = {
  "wifi": "\u{e1ae}",
  "wifi-off": "\u{e1af}",
  "wifi-low": "\u{e5f8}",
  "wifi-zero": "\u{e5f9}",
  "bluetooth": "\u{e05c}",
  "bluetooth-off": "\u{e1b9}",
  "bluetooth-connected": "\u{e1b8}",
  "bluetooth-searching": "\u{e1ba}",
  "volume": "\u{e1a9}",
  "volume-1": "\u{e1aa}",
  "volume-2": "\u{e1ab}",
  "volume-x": "\u{e1ac}",
  "sun": "\u{e178}",
  "sun-medium": "\u{e2b1}",
  "sun-dim": "\u{e299}",
  "moon": "\u{e11e}",
  "battery": "\u{e053}",
  "battery-charging": "\u{e054}",
  "battery-full": "\u{e055}",
  "battery-medium": "\u{e057}",
  "battery-low": "\u{e056}",
  "battery-warning": "\u{e3ac}",
  "play": "\u{e13c}",
  "pause": "\u{e12e}",
  "skip-back": "\u{e15f}",
  "skip-forward": "\u{e160}",
  "disc": "\u{e0af}",
  "music": "\u{e122}",
  "camera": "\u{e064}",
  "video": "\u{e1a5}",
  "settings": "\u{e154}",
  "refresh-cw": "\u{e145}",
  "rotate-cw": "\u{e149}",
  "power": "\u{e140}",
  "lock": "\u{e10b}",
  "unlock": "\u{e10c}",
  "link": "\u{e102}",
  "link-2": "\u{e103}",
  "headphones": "\u{e0f1}",
  "speaker": "\u{e166}",
  "mouse": "\u{e28e}",
  "keyboard": "\u{e284}",
  "gamepad-2": "\u{e0df}",
  "smartphone": "\u{e163}",
  "bell": "\u{e059}",
  "bell-off": "\u{e05a}",
  "timer": "\u{e1e0}",
  "clock": "\u{e087}",
  "check": "\u{e06c}",
  "x": "\u{e1b2}",
  "radio": "\u{e142}",
} as const

export default Lucide
