import GLib from "gi://GLib?version=2.0"
import Gio from "gi://Gio?version=2.0"
import { Lucide } from "./icons"

export type PackageCategory =
  | "runtimes"
  | "browsers"
  | "api"
  | "styling"
  | "ide"
  | "vcs"
  | "ai"
  | "backend"
  | "mobile"
  | "terminals"

export interface PackageDefinition {
  id: string
  name: string
  category: PackageCategory
  categoryLabel: string
  description: string
  tags: string[]
  icon: string
  color: string
  defaultSelected: boolean
  checkCmd: string
  installCmd: string
}

export const CATEGORIES: { id: PackageCategory | "all"; label: string; icon: string }[] = [
  { id: "all", label: "All Tools", icon: Lucide["grid"] },
  { id: "runtimes", label: "Runtimes & Pkg Mgrs", icon: Lucide["cpu"] },
  { id: "ide", label: "IDEs & Editors", icon: Lucide["code-2"] },
  { id: "ai", label: "AI Coding Agents", icon: Lucide["bot"] },
  { id: "backend", label: "Backend & DBs", icon: Lucide["database"] },
  { id: "mobile", label: "Mobile Dev", icon: Lucide["smartphone"] },
  { id: "terminals", label: "Terminals & Shell", icon: Lucide["terminal"] },
  { id: "browsers", label: "Browsers", icon: Lucide["globe"] },
  { id: "styling", label: "CSS & Styling", icon: Lucide["palette"] },
  { id: "vcs", label: "Version Control", icon: Lucide["git-branch"] },
  { id: "api", label: "API Tools", icon: Lucide["send"] },
]

export const PACKAGE_CATALOG: PackageDefinition[] = [
  // 1. Runtimes & Package Managers
  {
    id: "nodejs",
    name: "Node.js, npm, pnpm & yarn",
    category: "runtimes",
    categoryLabel: "Runtimes",
    description: "JavaScript/TypeScript runtime engine with modern package managers (pnpm, yarn, fnm)",
    tags: ["node", "npm", "pnpm", "yarn", "javascript", "typescript"],
    icon: Lucide["boxes"],
    color: "#a6e3a1",
    defaultSelected: true,
    checkCmd: "which node && which npm",
    installCmd: "sudo dnf install -y nodejs npm && sudo npm install -g pnpm yarn fnm",
  },
  {
    id: "bun",
    name: "Bun Runtime",
    category: "runtimes",
    categoryLabel: "Runtimes",
    description: "Incredibly fast all-in-one JavaScript/TypeScript runtime, bundler, and package manager",
    tags: ["bun", "runtime", "speed", "fast"],
    icon: Lucide["zap"],
    color: "#f9e2af",
    defaultSelected: true,
    checkCmd: "which bun || test -f $HOME/.bun/bin/bun",
    installCmd: "curl -fsSL https://bun.sh/install | bash",
  },
  {
    id: "deno",
    name: "Deno",
    category: "runtimes",
    categoryLabel: "Runtimes",
    description: "Secure, zero-config runtime for JavaScript, TypeScript, and WebAssembly",
    tags: ["deno", "security", "typescript"],
    icon: Lucide["shield"],
    color: "#89dceb",
    defaultSelected: true,
    checkCmd: "which deno || test -f $HOME/.deno/bin/deno",
    installCmd: "curl -fsSL https://deno.land/install.sh | sh",
  },

  // 2. Browsers
  {
    id: "chrome",
    name: "Google Chrome",
    category: "browsers",
    categoryLabel: "Browsers",
    description: "Industry standard web browser with comprehensive Chrome DevTools suite",
    tags: ["chrome", "google", "devtools", "web"],
    icon: Lucide["globe"],
    color: "#fab387",
    defaultSelected: true,
    checkCmd: "which google-chrome || which google-chrome-stable",
    installCmd: "sudo dnf install -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm",
  },
  {
    id: "brave",
    name: "Brave Browser",
    category: "browsers",
    categoryLabel: "Browsers",
    description: "Privacy-focused Chromium-based browser with built-in ad/tracker blocking",
    tags: ["brave", "privacy", "chromium"],
    icon: Lucide["shield-check"],
    color: "#fab387",
    defaultSelected: true,
    checkCmd: "which brave-browser",
    installCmd: "sudo dnf install -y dnf-plugins-core && sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo && sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc && sudo dnf install -y brave-browser",
  },

  // 3. API Tools
  {
    id: "postman",
    name: "Postman",
    category: "api",
    categoryLabel: "API Client",
    description: "Complete API development environment for REST, GraphQL, gRPC, and WebSocket testing",
    tags: ["postman", "api", "rest", "graphql", "http"],
    icon: Lucide["send"],
    color: "#fab387",
    defaultSelected: true,
    checkCmd: "which postman || flatpak list | grep -i postman",
    installCmd: "flatpak install -y flathub com.getpostman.Postman || (curl -o /tmp/postman.tar.gz https://dl.pstmn.io/download/latest/linux_64 && sudo tar -xzf /tmp/postman.tar.gz -C /opt && sudo ln -sf /opt/Postman/Postman /usr/local/bin/postman)",
  },

  // 4. CSS & Styling
  {
    id: "tailwindcss",
    name: "Tailwind CSS CLI (Global)",
    category: "styling",
    categoryLabel: "Styling",
    description: "Official standalone Tailwind CSS v4 / v3 command-line compiler installed globally",
    tags: ["tailwind", "css", "styling", "frontend"],
    icon: Lucide["palette"],
    color: "#89dceb",
    defaultSelected: true,
    checkCmd: "which tailwindcss || npm list -g @tailwindcss/cli",
    installCmd: "sudo npm install -g @tailwindcss/cli tailwindcss",
  },

  // 5. IDEs & Editors
  {
    id: "vscode",
    name: "Visual Studio Code",
    category: "ide",
    categoryLabel: "IDEs & Editors",
    description: "Extensible code editor with Git integration, debugging, and rich extension ecosystem",
    tags: ["vscode", "code", "editor", "microsoft"],
    icon: Lucide["code"],
    color: "#58a6ff",
    defaultSelected: true,
    checkCmd: "which code",
    installCmd: "sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc && sudo sh -c 'echo -e \"[code]\\nname=Visual Studio Code\\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\\nenabled=1\\ngpgcheck=1\\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc\" > /etc/yum.repos.d/vscode.repo' && sudo dnf install -y code",
  },
  {
    id: "antigravity",
    name: "Antigravity IDE / agy CLI",
    category: "ide",
    categoryLabel: "IDEs & Editors",
    description: "Google Antigravity AI agentic coding assistant, IDE runtime, and command-line companion",
    tags: ["antigravity", "agy", "google", "ai", "agent"],
    icon: Lucide["sparkles"],
    color: "#cba6f7",
    defaultSelected: true,
    checkCmd: "which agy || which antigravity",
    installCmd: "sudo npm install -g @google/antigravity-cli",
  },

  // 6. Version Control
  {
    id: "git",
    name: "Git & Delta Diff",
    category: "vcs",
    categoryLabel: "Version Control",
    description: "Distributed version control system with syntax-highlighting diff pager",
    tags: ["git", "vcs", "diff", "delta"],
    icon: Lucide["git-branch"],
    color: "#f38ba8",
    defaultSelected: true,
    checkCmd: "which git",
    installCmd: "sudo dnf install -y git git-delta",
  },
  {
    id: "gh",
    name: "GitHub CLI (gh)",
    category: "vcs",
    categoryLabel: "Version Control",
    description: "Official command-line tool for GitHub pull requests, issues, releases, and auth",
    tags: ["gh", "github", "cli", "pr"],
    icon: Lucide["git-pull-request"],
    color: "#ffffff",
    defaultSelected: true,
    checkCmd: "which gh",
    installCmd: "sudo dnf install -y gh",
  },
  {
    id: "lazygit",
    name: "LazyGit Terminal UI",
    category: "vcs",
    categoryLabel: "Version Control",
    description: "Simple, keyboard-driven terminal UI for git commands, staging, branching, and rebasing",
    tags: ["lazygit", "tui", "terminal", "git"],
    icon: Lucide["folder-git-2"],
    color: "#a6e3a1",
    defaultSelected: true,
    checkCmd: "which lazygit",
    installCmd: "sudo dnf copr enable -y atim/lazygit && sudo dnf install -y lazygit",
  },

  // 7. AI Coding Agents
  {
    id: "claude-code",
    name: "Claude Code CLI",
    category: "ai",
    categoryLabel: "AI Agents",
    description: "Agentic coding companion by Anthropic that reads codebases, edits files, and runs tests",
    tags: ["claude", "anthropic", "agent", "ai", "cli"],
    icon: Lucide["bot"],
    color: "#fab387",
    defaultSelected: true,
    checkCmd: "which claude",
    installCmd: "sudo npm install -g @anthropic-ai/claude-code",
  },
  {
    id: "opencode",
    name: "OpenCode Interpreter",
    category: "ai",
    categoryLabel: "AI Agents",
    description: "Open-source natural language code execution and agent framework",
    tags: ["opencode", "open-interpreter", "ai", "python"],
    icon: Lucide["terminal"],
    color: "#89dceb",
    defaultSelected: false,
    checkCmd: "which opencode || which open-code",
    installCmd: "pip install --user opencode-interpreter || sudo npm install -g opencode",
  },
  {
    id: "mimocode",
    name: "MimoCode CLI",
    category: "ai",
    categoryLabel: "AI Agents",
    description: "AI-assisted coding helper and automated code generator for software projects",
    tags: ["mimocode", "mimo", "ai", "assistant"],
    icon: Lucide["sparkles"],
    color: "#cba6f7",
    defaultSelected: false,
    checkCmd: "which mimocode",
    installCmd: "sudo npm install -g mimocode || pip install --user mimocode",
  },
  {
    id: "aider",
    name: "Aider AI Pair Programmer",
    category: "ai",
    categoryLabel: "AI Agents",
    description: "AI pair programming in your terminal with Git auto-commits and multi-file editing",
    tags: ["aider", "gpt", "claude", "pair-programming"],
    icon: Lucide["message-square-code"],
    color: "#a6e3a1",
    defaultSelected: true,
    checkCmd: "which aider",
    installCmd: "pip install --user aider-chat",
  },

  // 8. Backend, Languages & Databases
  {
    id: "docker",
    name: "Docker Engine & Compose",
    category: "backend",
    categoryLabel: "Backend & DBs",
    description: "Enterprise container platform and multi-container Compose orchestration",
    tags: ["docker", "containers", "compose", "server"],
    icon: Lucide["container"],
    color: "#58a6ff",
    defaultSelected: true,
    checkCmd: "which docker",
    installCmd: "sudo dnf install -y dnf-plugins-core && sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo && sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && sudo systemctl enable --now docker && sudo usermod -aG docker $USER",
  },
  {
    id: "golang",
    name: "Go Programming Language",
    category: "backend",
    categoryLabel: "Backend & DBs",
    description: "High-performance compiled language for web servers, microservices, and CLI tools",
    tags: ["go", "golang", "backend", "cloud"],
    icon: Lucide["binary"],
    color: "#89dceb",
    defaultSelected: true,
    checkCmd: "which go",
    installCmd: "sudo dnf install -y golang",
  },
  {
    id: "python",
    name: "Python 3 & uv",
    category: "backend",
    categoryLabel: "Backend & DBs",
    description: "Python 3 developer environment with ultra-fast 'uv' package installer and resolver",
    tags: ["python", "uv", "pip", "backend", "ai"],
    icon: Lucide["file-code"],
    color: "#f9e2af",
    defaultSelected: true,
    checkCmd: "which python3 && which uv",
    installCmd: "sudo dnf install -y python3 python3-pip python3-devel && curl -LsSf https://astral.sh/uv/install.sh | sh",
  },
  {
    id: "dbeaver",
    name: "DBeaver Community Edition",
    category: "backend",
    categoryLabel: "Backend & DBs",
    description: "Universal multi-platform database administration tool for PostgreSQL, MySQL, SQLite, MongoDB",
    tags: ["dbeaver", "sql", "database", "postgres", "mysql"],
    icon: Lucide["database"],
    color: "#fab387",
    defaultSelected: true,
    checkCmd: "which dbeaver || flatpak list | grep -i dbeaver",
    installCmd: "sudo dnf install -y https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm || flatpak install -y flathub io.dbeaver.DBeaverCommunity",
  },

  // 9. Mobile Development
  {
    id: "android-tools",
    name: "Android Platform Tools & scrcpy",
    category: "mobile",
    categoryLabel: "Mobile Dev",
    description: "ADB, Fastboot, and high-performance physical Android screen mirroring / control",
    tags: ["adb", "android", "scrcpy", "mobile"],
    icon: Lucide["smartphone"],
    color: "#3cd070",
    defaultSelected: true,
    checkCmd: "which adb && which scrcpy",
    installCmd: "sudo dnf install -y android-tools scrcpy",
  },
  {
    id: "android-studio",
    name: "Android Studio IDE",
    category: "mobile",
    categoryLabel: "Mobile Dev",
    description: "Official IDE for Android app development, Jetpack Compose, Kotlin, and AVD emulators",
    tags: ["android", "studio", "kotlin", "java", "emulator"],
    icon: Lucide["smartphone"],
    color: "#3cd070",
    defaultSelected: true,
    checkCmd: "which studio || which android-studio || flatpak list | grep -i androidstudio",
    installCmd: "flatpak install -y flathub com.google.AndroidStudio",
  },
  {
    id: "react-native",
    name: "React Native CLI & Watchman",
    category: "mobile",
    categoryLabel: "Mobile Dev",
    description: "Cross-platform native mobile app toolchain for React Native and Expo",
    tags: ["react-native", "react", "expo", "ios", "android"],
    icon: Lucide["atom"],
    color: "#58a6ff",
    defaultSelected: true,
    checkCmd: "which react-native",
    installCmd: "sudo npm install -g react-native-cli @react-native-community/cli",
  },
  {
    id: "flutter",
    name: "Flutter SDK & Dart",
    category: "mobile",
    categoryLabel: "Mobile Dev",
    description: "Google UI toolkit for building natively compiled mobile, web, and desktop apps",
    tags: ["flutter", "dart", "mobile", "google"],
    icon: Lucide["feather"],
    color: "#58a6ff",
    defaultSelected: true,
    checkCmd: "which flutter",
    installCmd: "sudo dnf install -y git curl unzip && (git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter && echo 'export PATH=\"$HOME/flutter/bin:$PATH\"' >> $HOME/.bashrc)",
  },

  // 10. Modern Terminals & Shells
  {
    id: "terminals",
    name: "Modern Terminals (Ptyxis, Kitty, Alacritty, Foot)",
    category: "terminals",
    categoryLabel: "Terminals & Shell",
    description: "GPU-accelerated Wayland/Hyprland terminal suite for Fedora",
    tags: ["terminal", "kitty", "alacritty", "foot", "ptyxis"],
    icon: Lucide["terminal"],
    color: "#a6e3a1",
    defaultSelected: true,
    checkCmd: "which kitty && which alacritty && which foot",
    installCmd: "sudo dnf install -y kitty alacritty foot ptyxis",
  },
  {
    id: "shells",
    name: "Zsh, Fish & Starship Prompt",
    category: "terminals",
    categoryLabel: "Terminals & Shell",
    description: "Modern interactive shells with blazing-fast cross-shell Starship prompt",
    tags: ["zsh", "fish", "starship", "shell", "prompt"],
    icon: Lucide["command"],
    color: "#f38ba8",
    defaultSelected: true,
    checkCmd: "which zsh && which starship",
    installCmd: "sudo dnf install -y zsh fish && curl -sS https://starship.rs/install.sh | sh -s -- -y",
  },
  {
    id: "cli-tools",
    name: "Modern CLI Tools (eza, bat, rg, fd, btop)",
    category: "terminals",
    categoryLabel: "Terminals & Shell",
    description: "Next-generation replacements for ls, cat, grep, find, and top with color & git status",
    tags: ["eza", "bat", "ripgrep", "fd", "btop"],
    icon: Lucide["hard-drive"],
    color: "#cba6f7",
    defaultSelected: true,
    checkCmd: "which eza && which bat && which rg && which btop",
    installCmd: "sudo dnf install -y eza bat ripgrep fd-find btop wl-clipboard",
  },
  {
    id: "fonts",
    name: "JetBrains Mono & Fira Code Nerd Fonts",
    category: "terminals",
    categoryLabel: "Terminals & Shell",
    description: "Developer coding fonts with ligatures and complete icon glyph coverage",
    tags: ["font", "nerd-font", "jetbrains", "fira-code"],
    icon: Lucide["type"],
    color: "#ffffff",
    defaultSelected: true,
    checkCmd: "fc-list | grep -i 'JetBrainsMono'",
    installCmd: "sudo dnf install -y jetbrains-mono-fonts fira-code-fonts google-noto-sans-fonts",
  },
]
