// Lucide icon font mapping for File Explorer
export const Lucide = {
  "folder": "\u{e0d8}",
  "folder-open": "\u{e0db}",
  "folder-plus": "\u{e0dc}",
  "folder-git": "\u{e0d9}",
  "file": "\u{e0cb}",
  "file-text": "\u{e0d5}",
  "file-code": "\u{e0ce}",
  "file-archive": "\u{e0cc}",
  "file-audio": "\u{e0cd}",
  "file-image": "\u{e0d0}",
  "file-video": "\u{e0d7}",
  "image": "\u{e0f8}",
  "music": "\u{e122}",
  "video": "\u{e1a5}",
  "archive": "\u{e049}",
  "home": "\u{e0f3}",
  "download": "\u{e0b3}",
  "trash": "\u{e18e}",
  "trash-2": "\u{e18f}",
  "hard-drive": "\u{e0ed}",
  "monitor": "\u{e11d}",
  "terminal": "\u{e17f}",
  "search": "\u{e152}",
  "arrow-left": "\u{e050}",
  "arrow-right": "\u{e051}",
  "arrow-up": "\u{e052}",
  "rotate-cw": "\u{e149}",
  "refresh-cw": "\u{e145}",
  "chevron-right": "\u{e07b}",
  "chevron-down": "\u{e079}",
  "grid": "\u{e0eb}",
  "list": "\u{e106}",
  "eye": "\u{e0c7}",
  "eye-off": "\u{e0c8}",
  "plus": "\u{e13d}",
  "x": "\u{e1b2}",
  "copy": "\u{e08e}",
  "external-link": "\u{e0c6}",
  "more-horizontal": "\u{e120}",
  "info": "\u{e0fa}",
} as const

export default Lucide
